"""Trigger entry for the find-peaks Action.

A small, separate entry rather than a button on the XPS entry itself, since
that entry's structure is generated by pynxtools-xps -- referencing it is
preferred over modifying generated code.
"""

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from nomad.datamodel.datamodel import EntryArchive
    from structlog.stdlib import BoundLogger

from nomad.actions.manager import get_action_status, start_action
from nomad.datamodel.data import ArchiveSection, EntryData
from nomad.datamodel.metainfo.annotations import ELNAnnotation, ELNComponentEnum
from nomad.metainfo import Quantity, SchemaPackage

from nomad_eosc_galaxy_actions.actions.find_peaks.models import FindPeaksWorkflowInput

m_package = SchemaPackage()


class FindPeaksTrigger(EntryData):
    """Triggers the find-peaks Action for a referenced XPS spectrum entry.

    Currently wired to an empty-run Action skeleton: `workflow_status` reaching
    `COMPLETED` confirms the Temporal round trip and this entry's UI, before
    any real NeXus reading or Galaxy call is added to the activity.
    """

    spectrum = Quantity(
        type=ArchiveSection,
        description='The source XPS spectrum entry to find peaks in.',
        a_eln=ELNAnnotation(component=ELNComponentEnum.ReferenceEditQuantity),
    )
    workflow_id = Quantity(
        type=str,
        description='Unique ID of the triggered workflow run.',
    )
    workflow_status = Quantity(
        type=str,
        description='Status of the workflow run: RUNNING, COMPLETED, FAILED, ...',
    )
    result_entry = Quantity(
        type=ArchiveSection,
        description=(
            'The new entry holding the original spectrum and detected peaks, '
            'once the Action completes. Not yet wired up in this skeleton.'
        ),
        a_eln=ELNAnnotation(component=ELNComponentEnum.ReferenceEditQuantity),
    )

    trigger_find_peaks = Quantity(
        type=bool,
        description='Starts an asynchronous run of the find-peaks action.',
        a_eln=ELNAnnotation(
            component=ELNComponentEnum.ActionEditQuantity,
            label='Find Peaks',
        ),
    )
    trigger_get_status = Quantity(
        type=bool,
        description='Fetches the status for the current workflow run.',
        a_eln=ELNAnnotation(
            component=ELNComponentEnum.ActionEditQuantity,
            label='Get Action Status',
        ),
    )

    def run_find_peaks(self, archive: 'EntryArchive', logger: 'BoundLogger') -> None:
        if not self.spectrum:
            logger.warning('No spectrum referenced. Cannot start the find-peaks action.')
            return
        self.workflow_status = None
        self.workflow_id = None
        input_data = FindPeaksWorkflowInput(
            user_id=archive.metadata.authors[0].user_id,
            upload_id=archive.metadata.upload_id,
            spectrum_entry_id=self.spectrum.m_root().metadata.entry_id,
        )
        self.workflow_id = start_action(
            action_id='nomad_eosc_galaxy_actions.actions.find_peaks:find_peaks_action',
            data=input_data,
        )
        self.trigger_get_status = True

    def normalize(self, archive: 'EntryArchive', logger: 'BoundLogger') -> None:
        super().normalize(archive, logger)
        if self.trigger_find_peaks:
            if self.workflow_status == 'RUNNING':
                logger.warning('A run is already in progress.')
            else:
                self.run_find_peaks(archive, logger)
            self.trigger_find_peaks = False
        if self.trigger_get_status:
            if self.workflow_id:
                try:
                    status = get_action_status(
                        self.workflow_id, archive.metadata.authors[0].user_id
                    )
                    self.workflow_status = status.name
                except Exception as e:
                    logger.error(f'Error getting workflow status: {e}')
            self.trigger_get_status = False


m_package.__init_metainfo__()
